language: go

go: 1.7.4

sudo: required

services:
 - docker

install:
#  - cd $TRAVIS_BUILD_DIR
#  - go version
  - go get -u github.com/Masterminds/glide
  - glide install
  - go build

deploy:
  steps:
    - internal/docker-push:
        username: $DOCKER_USERNAME
        password: $DOCKER_PASSWORD
        cmd: /pipeline/source/hello
        port: "8080"
        tag: latest
        repository: cloudnativego/book-hello
        registry: https://registry.hub.docker.com