language: go

go: 1.7.4

sudo: required

services:
 - docker

install:
#  - cd $TRAVIS_BUILD_DIR
#  - go version
  - go get -u github.com/Masterminds/glide
  - glide install
  - go build

# https://docs.travis-ci.com/user/docker/
after_success:
  - if [ "$TRAVIS_BRANCH" == "master"]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push austinba/helloapp;
    fi